### ISSUE TITLE
Adding load more

### ISSUE THREAD

**Issue by TrixieL** [xuopled/react-responsive-masonry#5]
@xuopled  Hi Cedric!

Again, thanks for answering my emails. I was wondering if we can have a feature which loads more photos when a button is clicked (in contrast with infinite scrolling). The number of photos shown by default as well as the number of photos to be loaded should be customizable; considering different screen sizes (mobiles and desktop).

Thanks!! :)

**Comment by xuopled** [comment]
Hi, you can achieve this with a custom wrapper. It is not the responsibility of react-responsive-masonry. 

```js
class MyWrapper extends Component {
  constructor() {
    this.state = {
      images = []
  }

  loadMore() {
   // Your load more magic
    this.setState({images: newImages})
  }

  render() {
    return (
        <ResponsiveMasonry columnsCountBreakPoints={{350: 1, 750: 2, 900: 3}}>
        	<Masonry>
        		{this.state.images.map((image, i) =>
        			<img key={i} src={image} style={{width: "100%", display: "block"}} />
        		)}
        	</Masonry>
    	</ResponsiveMasonry>
    )
  }
}
```

**Comment by pjc0247** [comment]
<img width="1885" height="994" alt="Image" src="https://github.com/user-attachments/assets/8ecf0dea-85d2-4d7e-9146-7fbd3bbe73f5" />

When using MasonryList, it's hard to know when to load the next page because each column has a different height. If even one of the columns shows an empty space, the next page should be loaded.

So I solved it like this, but it would be better if the library supported it.


```tsx
const Cell = () => {
  return (
    <Impression
      onImpression={() => {
            if (containerRef.current != null) {
              const parent = containerRef.current.parentElement?.parentElement;
              // Am I the last item in the column?
              if (parent?.nextSibling == null) {
                onLoadMore();
              }
            }
      }}
    >
      <Container ref={containerRef}>
        <dosomething />
      </Container>
    </Impression>
  );
};
```


The Impression component is a utility that wraps something like the following.

https://www.npmjs.com/package/react-intersection-observer
